-- NETTOYAGE DES DONNEES EXISTANTES
DELETE FROM ActivitesApprentissage;
DELETE FROM Inscriptions;
DELETE FROM CoursEnseignes;
DELETE FROM CoursPrealables;
DELETE FROM AdresseCivique;
DELETE FROM Cours;
DELETE FROM Etudiants;
DELETE FROM Enseignants;
UPDATE Departements SET DepartementDirecteur = NULL;
DELETE FROM Departements;
DELETE FROM Personnes;

-- Reset des sequences
DROP SEQUENCE SEQ_DEPARTEMENTS;
DROP SEQUENCE SEQ_PERSONNES;
DROP SEQUENCE SEQ_COURS;
DROP SEQUENCE SEQ_ADDR_CIVIQUE;

CREATE SEQUENCE SEQ_DEPARTEMENTS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PERSONNES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_COURS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ADDR_CIVIQUE START WITH 1 INCREMENT BY 1;

COMMIT;